### ISSUE TITLE
자동 검사 실행 실패: 권한 부족

### ISSUE THREAD

**Issue by changwoo-ivy** [wpkorea/ivy-utils#8]
디렉토리의 읽기 권한이 부족한 경우 용량 체크가 제대로 되지 않습니다.

```
PHP Fatal error:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct({PATH}): failed to open dir: Permission denied in {PATH}/public_html/wp-content/plugins/ivy-utils/modules/disk-usage/disk-usage.php:64
Stack trace:
#0 {PATH}/public_html/wp-content/plugins/ivy-utils/modules/disk-usage/disk-usage.php(64): RecursiveDirectoryIterator->__construct('{PATH}....')
#1 {PATH}/public_html/wp-content/plugins/ivy-utils/modules/disk-usage/disk-usage.php(145): ivut_disk_usage_get_directory_size('{PATH}....')
#2 {PATH}/public_html/wp-content/plugins/ivy-utils/modules/disk-usage/disk-usage.php(360): ivut_disk_usage_get_used_size(true)
#3 {PATH}/public_html/wp-includes/class-wp-hook.php(286): ivut_disk_usage_check_directory_size()
#4 {PATH}/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#5 {PATH}/public_html/wp- in {PATH}/public_html/wp-content/plugins/ivy-utils/modules/disk-usage/disk-usage.php on line 64
```

**Comment by changwoo-ivy** [comment]
버전 1.0.1 에서 처리될 예정입니다. 설정 저장시 디렉토리인지 검사하고, 또 디렉토리의 읽기/실행 권한을 체크하여 적절하지 않은 디렉토리가 입력되는 경우 기본값인 워드프레스 디렉토리를 설정하도록 기능을 향상합니다.

또한 설정 저장시 메시지도 같이 출력되도록 합니다.

**Comment by changwoo-ivy** [comment]
e726107b, c771b2e4 에서 처리되었습니다. 열람 권한이 부족한 경우 기본 워드프레스 디렉토리로 설정되도록 동작합니다. 이슈를 종료합니다.
